// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests the best team member to assign a new responsibility to.
 *
 * - assignResponsibility - A function that suggests the best team member for a new responsibility.
 * - AssignResponsibilityInput - The input type for the assignResponsibility function.
 * - AssignResponsibilityOutput - The return type for the assignResponsibility function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssignResponsibilityInputSchema = z.object({
  responsibility: z.string().describe('The new responsibility to be assigned.'),
  teamMembers: z
    .array(z.object({
      name: z.string().describe('The name of the team member.'),
      currentTasks: z.array(z.string()).describe('The current tasks assigned to the team member.'),
      upcomingDeadlines: z
        .array(z.string())
        .describe('The upcoming deadlines for the team member (ISO date format).'),
    }))
    .describe('The list of team members and their current workload.'),
});
export type AssignResponsibilityInput = z.infer<typeof AssignResponsibilityInputSchema>;

const AssignResponsibilityOutputSchema = z.object({
  suggestedTeamMember: z
    .string()
    .describe('The name of the team member suggested for the new responsibility.'),
  reasoning: z
    .string()
    .describe('The reasoning behind the suggestion, considering workload and deadlines.'),
});
export type AssignResponsibilityOutput = z.infer<typeof AssignResponsibilityOutputSchema>;

export async function assignResponsibility(
  input: AssignResponsibilityInput
): Promise<AssignResponsibilityOutput> {
  return assignResponsibilityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'assignResponsibilityPrompt',
  input: {schema: AssignResponsibilityInputSchema},
  output: {schema: AssignResponsibilityOutputSchema},
  prompt: `You are an AI assistant helping to manage team responsibilities. Given a new responsibility and a list of team members with their current tasks and upcoming deadlines, suggest the best team member to assign the new responsibility to. Consider their current workload and upcoming deadlines to avoid overburdening any one individual.

New Responsibility: {{{responsibility}}}

Team Members:
{{#each teamMembers}}
- Name: {{{name}}}
  Current Tasks: {{#each currentTasks}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  Upcoming Deadlines: {{#each upcomingDeadlines}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}

Based on this information, who is the best team member to assign this new responsibility to? Explain your reasoning.

Suggested Team Member: {{suggestedTeamMember}}
Reasoning: {{reasoning}}`,
});

const assignResponsibilityFlow = ai.defineFlow(
  {
    name: 'assignResponsibilityFlow',
    inputSchema: AssignResponsibilityInputSchema,
    outputSchema: AssignResponsibilityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
