// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests the best team member to assign a new task to.
 *
 * - assignTask - A function that suggests the best team member for a new task.
 * - AssignTaskInput - The input type for the assignTask function.
 * - AssignTaskOutput - The return type for the assignTask function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssignTaskInputSchema = z.object({
  task: z.string().describe('La nueva tarea a asignar.'),
  teamMembers: z
    .array(z.object({
      name: z.string().describe('El nombre del miembro del equipo.'),
      currentTasks: z.array(z.string()).describe('Las tareas actuales asignadas al miembro del equipo.'),
      upcomingDeadlines: z
        .array(z.string())
        .describe('Las próximas fechas límite para el miembro del equipo (formato de fecha ISO).'),
    }))
    .describe('La lista de miembros del equipo y su carga de trabajo actual.'),
});
export type AssignTaskInput = z.infer<typeof AssignTaskInputSchema>;

const AssignTaskOutputSchema = z.object({
  suggestedTeamMember: z
    .string()
    .describe('El nombre del miembro del equipo sugerido para la nueva tarea.'),
  reasoning: z
    .string()
    .describe('El razonamiento detrás de la sugerencia, considerando la carga de trabajo y las fechas límite.'),
});
export type AssignTaskOutput = z.infer<typeof AssignTaskOutputSchema>;

export async function assignTask(
  input: AssignTaskInput
): Promise<AssignTaskOutput> {
  return assignTaskFlow(input);
}

const prompt = ai.definePrompt({
  name: 'assignTaskPrompt',
  input: {schema: AssignTaskInputSchema},
  output: {schema: AssignTaskOutputSchema},
  prompt: `Eres un asistente de IA que ayuda a gestionar las tareas del equipo. Dada una nueva tarea y una lista de miembros del equipo con sus tareas actuales y próximas fechas límite, sugiere el mejor miembro del equipo para asignar la nueva tarea. Considera su carga de trabajo actual y las próximas fechas límite para evitar sobrecargar a cualquier individuo.

Nueva Tarea: {{{task}}}

Miembros del equipo:
{{#each teamMembers}}
- Nombre: {{{name}}}
  Tareas actuales: {{#each currentTasks}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  Próximas fechas límite: {{#each upcomingDeadlines}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}

Basado en esta información, ¿quién es el mejor miembro del equipo para asignar esta nueva tarea? Explica tu razonamiento.

Miembro del equipo sugerido: {{suggestedTeamMember}}
Razonamiento: {{reasoning}}`,
});

const assignTaskFlow = ai.defineFlow(
  {
    name: 'assignTaskFlow',
    inputSchema: AssignTaskInputSchema,
    outputSchema: AssignTaskOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
