// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests the best team member to assign a new responsibility to.
 *
 * - assignResponsibility - A function that suggests the best team member for a new responsibility.
 * - AssignResponsibilityInput - The input type for the assignResponsibility function.
 * - AssignResponsibilityOutput - The return type for the assignResponsibility function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssignResponsibilityInputSchema = z.object({
  responsibility: z.string().describe('La nueva responsabilidad a asignar.'),
  teamMembers: z
    .array(z.object({
      name: z.string().describe('El nombre del miembro del equipo.'),
      currentTasks: z.array(z.string()).describe('Las tareas actuales asignadas al miembro del equipo.'),
      upcomingDeadlines: z
        .array(z.string())
        .describe('Las próximas fechas límite para el miembro del equipo (formato de fecha ISO).'),
    }))
    .describe('La lista de miembros del equipo y su carga de trabajo actual.'),
});
export type AssignResponsibilityInput = z.infer<typeof AssignResponsibilityInputSchema>;

const AssignResponsibilityOutputSchema = z.object({
  suggestedTeamMember: z
    .string()
    .describe('El nombre del miembro del equipo sugerido para la nueva responsabilidad.'),
  reasoning: z
    .string()
    .describe('El razonamiento detrás de la sugerencia, considerando la carga de trabajo y las fechas límite.'),
});
export type AssignResponsibilityOutput = z.infer<typeof AssignResponsibilityOutputSchema>;

export async function assignResponsibility(
  input: AssignResponsibilityInput
): Promise<AssignResponsibilityOutput> {
  return assignResponsibilityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'assignResponsibilityPrompt',
  input: {schema: AssignResponsibilityInputSchema},
  output: {schema: AssignResponsibilityOutputSchema},
  prompt: `Eres un asistente de IA que ayuda a gestionar las responsabilidades del equipo. Dada una nueva responsabilidad y una lista de miembros del equipo con sus tareas actuales y próximas fechas límite, sugiere el mejor miembro del equipo para asignar la nueva responsabilidad. Considera su carga de trabajo actual y las próximas fechas límite para evitar sobrecargar a cualquier individuo.

Nueva Responsabilidad: {{{responsibility}}}

Miembros del equipo:
{{#each teamMembers}}
- Nombre: {{{name}}}
  Tareas actuales: {{#each currentTasks}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  Próximas fechas límite: {{#each upcomingDeadlines}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}

Basado en esta información, ¿quién es el mejor miembro del equipo para asignar esta nueva responsabilidad? Explica tu razonamiento.

Miembro del equipo sugerido: {{suggestedTeamMember}}
Razonamiento: {{reasoning}}`,
});

const assignResponsibilityFlow = ai.defineFlow(
  {
    name: 'assignResponsibilityFlow',
    inputSchema: AssignResponsibilityInputSchema,
    outputSchema: AssignResponsibilityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
