// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import { FirebaseOptions } from 'firebase/app';

// This is a placeholder for the Firebase config object.
// It will be replaced with the actual config when the app is built.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
  measurementId: "YOUR_MEASUREMENT_ID"
};
