// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import { FirebaseOptions } from 'firebase/app';

// This is a placeholder for the Firebase config object.
// It will be replaced with the actual config when the app is built.
export const firebaseConfig: FirebaseOptions = {
  projectId: 'studio-3324096154-db37c',
  appId: '1:937237542995:web:9747339171e5b51826aea6',
  apiKey: 'AIzaSyANSV5E_F3vZOezHmyX4T8ZHjK0FW00Z5w',
  authDomain: 'studio-3324096154-db37c.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '937237542995',
  storageBucket: 'studio-3324096154-db37c.appspot.com'
};
